CREATE TABLE APP_USER (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(64),
    PASSWORD_HASH VARCHAR(512),
    LAST_PASSWORD_CHANGE DATETIME,
    PRIMARY KEY (ID),
    UNIQUE (USERNAME)
);
